server:
  port: ${PORT:8000}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:projec-1}
    jackson:
      time-zone: America/Sao_Paulo

  datasource:
    username: ${DB_USER:project-1}
    password: ${DB_PASSWORD:project-1}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:project-1}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
